"""estructura inicial

Revision ID: 3ceb04dfb478
Revises: 
Create Date: 2026-05-26 01:08:21.459649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ceb04dfb478'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=150), nullable=False),
    sa.Column('apellidos', sa.String(length=150), nullable=False),
    sa.Column('usuario', sa.String(length=80), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('cargo', sa.String(length=120), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('correspondencia_entrada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hoja_ruta', sa.String(length=50), nullable=False),
    sa.Column('cite', sa.String(length=100), nullable=True),
    sa.Column('remitente', sa.String(length=255), nullable=False),
    sa.Column('institucion_remitente', sa.String(length=255), nullable=True),
    sa.Column('referencia', sa.String(length=500), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('prioridad', sa.String(length=30), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('area_destino', sa.String(length=150), nullable=True),
    sa.Column('fecha_documento', sa.Date(), nullable=True),
    sa.Column('fecha_limite', sa.Date(), nullable=True),
    sa.Column('requiere_respuesta', sa.Boolean(), nullable=True),
    sa.Column('urgente', sa.Boolean(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('archivo', sa.String(length=255), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hoja_ruta')
    )
    op.create_table('correspondencia_salida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hoja_ruta', sa.String(length=50), nullable=False),
    sa.Column('cite', sa.String(length=100), nullable=True),
    sa.Column('destinatario', sa.String(length=255), nullable=False),
    sa.Column('institucion_destino', sa.String(length=255), nullable=True),
    sa.Column('referencia', sa.String(length=500), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('prioridad', sa.String(length=30), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('medio_envio', sa.String(length=100), nullable=True),
    sa.Column('numero_guia', sa.String(length=100), nullable=True),
    sa.Column('fecha_envio', sa.Date(), nullable=True),
    sa.Column('fecha_entrega', sa.Date(), nullable=True),
    sa.Column('recibido_por', sa.String(length=255), nullable=True),
    sa.Column('confirmado', sa.Boolean(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('archivo', sa.String(length=255), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hoja_ruta')
    )
    op.create_table('adjuntos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_original', sa.String(length=255), nullable=False),
    sa.Column('nombre_guardado', sa.String(length=255), nullable=False),
    sa.Column('ruta', sa.String(length=500), nullable=False),
    sa.Column('extension', sa.String(length=20), nullable=True),
    sa.Column('peso', sa.Integer(), nullable=True),
    sa.Column('fecha_subida', sa.DateTime(), nullable=True),
    sa.Column('entrada_id', sa.Integer(), nullable=True),
    sa.Column('salida_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entrada_id'], ['correspondencia_entrada.id'], ),
    sa.ForeignKeyConstraint(['salida_id'], ['correspondencia_salida.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seguimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=255), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('entrada_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entrada_id'], ['correspondencia_entrada.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seguimientos')
    op.drop_table('adjuntos')
    op.drop_table('correspondencia_salida')
    op.drop_table('correspondencia_entrada')
    op.drop_table('usuarios')
    op.drop_table('roles')
    # ### end Alembic commands ###
