"""tabla auditoria

Revision ID: 4cafb027c949
Revises: 202eb6993835
Create Date: 2026-06-03 12:52:12.803240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cafb027c949'
down_revision = '202eb6993835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria_login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=100), nullable=True),
    sa.Column('ip', sa.String(length=50), nullable=True),
    sa.Column('exito', sa.Boolean(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intentos_fallidos', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bloqueado_hasta', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ultimo_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ultima_ip', sa.String(length=50), nullable=True))
        batch_op.alter_column('rol',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('rol',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.drop_column('ultima_ip')
        batch_op.drop_column('ultimo_login')
        batch_op.drop_column('bloqueado_hasta')
        batch_op.drop_column('intentos_fallidos')

    op.drop_table('auditoria_login')
    # ### end Alembic commands ###
